#!/bin/bash

# Automatically run at startup by editting crontab:
# `crontab -e`
# And adding line at end of file:
# `@reboot bash -l /home/ofirnachum/sleepnoise/sleepnoise`

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
NPREFIX=$SCRIPT_DIR/files
VOLATILE=/tmp
LOG_FILE=~/logs_sleepnoise.log
NOW=$(date "+%Y-%m-%d %H:%M:%S")

#noise="$NPREFIX/audiocheck.net_white_192k_-3dBFS.wav"
#noise="$NPREFIX/audiocheck.net_pink_192k_-3dBFS.wav"
noise="$NPREFIX/audiocheck.net_brownnoise.wav"

# copy wav to tmpfs for 0 disk usage
[[ -f "$VOLATILE/${noise##*/}" ]] || cp "$noise" "$VOLATILE"

get_volume() {
  currenttime=$(date +%H:%M)
  if [[ "$currenttime" < "06:00" ]]
  then
    echo "0.0"
  elif [[ "$currenttime" < "06:30" ]]
  then
    echo "0.5"
  elif [[ "$currenttime" < "09:00" ]]
  then
    echo "1"
  elif [[ "$currenttime" < "17:00" ]]
  then
    echo "0.5"
  elif [[ "$currenttime" < "20:30" ]]
  then
    echo "1"
  elif [[ "$currenttime" < "21:00" ]]
  then
    echo "0.8"
  elif [[ "$currenttime" < "21:30" ]]
  then
    echo "0.6"
  else
    echo "0"
noise="$NPREFIX/audiocheck.net_pink_192k_-3dBFS.wav"
  fi
}

play_sound() {
  volume=$1
  repeats=$2
  echo "$NOW ${noise##*/} $repeats" >> $LOG_FILE
  AUDIODEV=hw:2,0 play --volume=$volume -q -c 2 "$VOLATILE/${noise##*/}" repeat $repeats >/dev/null
  #play --volume=$volume -q -c 2 "$VOLATILE/${noise##*/}" repeat $repeats >/dev/null
}

while true
do
  volume=$(get_volume)
  echo $volume >> $LOG_FILE
  play_sound $volume 100
done
