#!/bin/bash

# Automatically run at startup by editting crontab:
# `crontab -e`
# And adding line at end of file:
# `@reboot bash -l /home/ofirnachum/sleepnoise/sleepnoise`

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
NPREFIX=$SCRIPT_DIR/files
SCHEDULE=$SCRIPT_DIR/schedule.txt
VOLATILE=/tmp
LOG_FILE=~/logs_sleepnoise.log
NOW=$(date "+%Y-%m-%d %H:%M:%S")

#noise="$NPREFIX/audiocheck.net_white_192k_-3dBFS.wav"
#noise="$NPREFIX/audiocheck.net_pink_192k_-3dBFS.wav"
noise="$NPREFIX/audiocheck.net_brownnoise.wav"

# copy wav to tmpfs for 0 disk usage
[[ -f "$VOLATILE/${noise##*/}" ]] || cp "$noise" "$VOLATILE"

get_volume() {
  currenttime=$(date +%H:%M)
  currenttimestamp=$(date +%s)
  while IFS="" read -r p || [ -n "$p" ]
  do
    IFS=" " read -r entry volume endtime <<< "$p"
    if [[ "$entry" == "override" ]] && [[ "$currenttimestamp" < "$endtime" ]]
    then
      break
    elif [[ "$entry" == "set" ]] && [[ "$currenttime" < "$endtime" ]]
    then
      break
    else
      continue
    fi
  done < $SCHEDULE
  echo "$volume"
}

while true
do
  volume=$(get_volume)
  echo "volume" $volume >> $LOG_FILE
  repeats=100
  echo "$NOW ${noise##*/} $repeats" >> $LOG_FILE
  AUDIODEV=hw:2,0 play --volume=$volume -q -c 2 "$VOLATILE/${noise##*/}" repeat $repeats >/dev/null
done
